FROM adoptopenjdk/openjdk11:alpine
VOLUME /tmp
COPY target/ApiConfigServer-0.0.1-SNAPSHOT.jar ApiConfigServer.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-jar", "ApiConfigServer.jar" ]